locations:
  kitchen:
    x: 1.0
    y: 0.0
  table1:
    x: 2.0
    y: 1.0
  table2:
    x: 2.0
    y: -1.0
  table3:
    x: 3.0
    y: 0.0
  home:
    x: 0.0
    y: 0.0

timeouts:
  navigation: 10  # Timeout in seconds for reaching a location
  confirmation: 5  # Timeout in seconds for receiving confirmation
